#ifndef _WSCERROR_H_INCLUDED
#define _WSCERROR_H_INCLUDED


#define ERR_WSC_ROMSIZE			-2
#define ERR_WSC_FILEOPEN		-3
#define ERR_WSC_FILEREAD		-4
#define ERR_WSC_NOROMDATA		-5
#define ERR_WSC_ROMTOOBIG		-6
#define ERR_WSC_MALLOC			-7
#define ERR_WSC_REALLOC			-8
#define ERR_WSC_FILESAVE		-9
#define ERR_WSC_FILESIZE		-10
#define ERR_WSC_FILESTAT		-11
#define ERR_WSC_ROMALIGNMENT	-12
#define ERR_WSC_ROMTEXTTOOBIG	-13


#define ERR_WSC_SYMNOTFOUND				-100
#define ERR_WSC_SYMNOTFOUND_BEGDATA		-100
#define ERR_WSC_SYMNOTFOUND_ENDDATA		-101
#define ERR_WSC_SYMNOTFOUND_BEGBSS		-102
#define ERR_WSC_SYMNOTFOUND_ENDBSS		-103
#define ERR_WSC_SYMNOTFOUND_ROMSTART	-104
#define ERR_WSC_SYMNOTFOUND_ROMEND		-105
#define ERR_WSC_SYMNOTFOUND_BEGROMDATA	-106



#endif  /* _WSCERROR_H_INCLUDED */