parameters:
  arch:     ''
  title:    ''
  doctype:  ''

jobs:
  - job: docs${{ parameters.doctype }}
    displayName: "${{ parameters.title }}"
    timeoutInMinutes: 90
    variables:
      ${{ if eq(parameters.arch, 'lnx') }}:
        owtools:        $(owtools_lnx)
        owtoolsv:       $(owtoolsv_lnx)
        owscript:       $(owscript_lnx)
      ${{ if eq(parameters.arch, 'nt') }}:
        owtools:        $(owtools_nt)
        owtoolsv:       $(owtoolsv_nt)
        owscript:       $(owscript_nt)
      ${{ if eq(parameters.doctype, 'docdos') }}:
        owdoctarget:    docdos
      ${{ if eq(parameters.doctype, 'dochtml') }}:
        owdoctarget:    dochtmlhelp
      ${{ if eq(parameters.doctype, 'docnt') }}:
        owdoctarget:    docnt
      ${{ if eq(parameters.doctype, 'docos2') }}:
        owdoctarget:    docos2
      ${{ if eq(parameters.doctype, 'docpdf') }}:
        owdoctarget:    docpdf
      ${{ if eq(parameters.doctype, 'docwin') }}:
        owdoctarget:    docwin
      owbuild.stage:    docs
    pool:
      ${{ if eq(parameters.arch, 'lnx') }}:
        vmImage: $(owimage_lnx)
      ${{ if eq(parameters.arch, 'nt') }}:
        vmImage: $(owimage_nt)
    steps:
    - template: artfload.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
    - script: $(owscript)
      displayName: "Documentation Build"
    - template: artfsave.yml
      parameters:
        path:       rel
        artifname:  rel-${{ parameters.doctype }}
