parameters:
  title:    ''

jobs:
  - job: lastbuild
    displayName: "${{ parameters.title }}"
    variables:
      owtools:          $(owtools_lnx)
      owtoolsv:         $(owtoolsv_lnx)
      owscript:         $(owscript_lnx)
      owbuild.stage:    inst
      owtag:            Last-CI-build
    pool:
      vmImage:      $(owimage_lnx)
    steps:
    - template: gituser.yml
    - checkout: self
      persistCredentials: true
    # consolidate binaries
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-nt
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-lnx
    # consolidate documentation
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-docdos
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-dochtml
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-docnt
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-docos2
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-docpdf
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-docwin
    # create full binary archive
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(owroot)/rel'
        includeRootFolder: false
        archiveType: 'tar'
        archiveFile: '$(owroot)/ow-snapshot.tar.gz'
        replaceExistingArchive: true
    - bash: echo "##vso[task.setvariable variable=owtagstamp;]`date +'%Y-%m-%d %H:%M:%S'`"
      displayName: "Get current timestamp"
    - bash: echo "##vso[task.setvariable variable=owgitstamp;]`git ls-remote --tags . | sed -n -e \"s:\([0-9a-z]*\) *refs/tags/${{ variables.owtag }}^{}:\1:p\"`"
      displayName: "Get 'Last-CI-build' tag commit"
    - script: |
        if [ ! "$OWGITSTAMP" = "$BUILD_SOURCEVERSION" ]; then
          git tag -d $OWTAG
          git push --delete origin $OWTAG
          git tag -a -m "$OWTAGSTAMP" $OWTAG $BUILD_SOURCEVERSION
          git push $(owgitverbose) origin $OWTAG
        else
          echo "##vso[task.setvariable variable=owtagstamp;]`git tag -l --format='%(contents)' $OWTAG`"
        fi
      displayName: "Recreate 'Last-CI-build' tag"
    - template: doreleas.yml
      parameters:
        arch:      'lnx'
        update:    'true'
        disp:      'Update Last-CI-build'
        title:     '$(owtag)'
        tag:       '$(owtag)'
        timestamp: '$(owtagstamp)'
